# Generated by Django 5.0.3 on 2024-07-24 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0003_newapikey"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="newApiKey",
            new_name="userApiKey",
        ),
        migrations.RenameField(
            model_name="userapikey",
            old_name="username",
            new_name="user",
        ),
    ]
