# Generated by Django 5.0 on 2024-07-27 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_apikey_delete_userapikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='updated_on',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='apikey',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
