# Generated by Django 5.0.3 on 2024-03-04 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_alter_plan_github_repos"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="benefits",
            field=models.JSONField(default=[], null=True),
        ),
        migrations.AlterField(
            model_name="price",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("day", "day"),
                    ("week", "week"),
                    ("month", "month"),
                    ("year", "year"),
                ],
                default="month",
                max_length=10,
                null=True,
            ),
        ),
    ]
