# Generated by Django 5.0.3 on 2024-03-05 17:34

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0004_alter_price_benefits_alter_price_frequency"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="features",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=500),
                default=[],
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="metadata",
            field=models.JSONField(blank=True, default={}, null=True),
        ),
    ]
