# Generated by Django 5.0.3 on 2024-03-05 17:35

import django_better_admin_arrayfield.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0005_alter_plan_features_alter_plan_metadata"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="features",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=500),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="github_repos",
            field=django_better_admin_arrayfield.models.fields.ArrayField(
                base_field=models.CharField(blank=True, max_length=200),
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="plan",
            name="metadata",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name="price",
            name="benefits",
            field=models.JSONField(default=list, null=True),
        ),
    ]
